name: Generate terraform docs
on:
  push:
    branches:
      - "main"
# For use with pull request 
# pull_request:
jobs:
  build:
    name: Documenation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
# For use with pull request 
#       ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        config-file: .terraform-docs.yml
        output-method: inject
        git-push: "true"
